// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var items = /* array */[
  10,
  11,
  12,
  13,
  14,
  15,
  16
];

console.log(items.length);

console.log(items.length);

var multiples = Belt_Array.make(5, 7.0);

console.log(multiples);

function sqrtPlusOne(x) {
  return Math.sqrt(x + 1.0);
}

var roots = Belt_Array.makeBy(5, sqrtPlusOne);

console.log(roots);

var more = /* array */[
  17,
  18,
  19
];

var joined = Belt_Array.concat(items, more);

console.log(joined);

var part1 = /* array */[
  "the",
  "array",
  "has"
];

var part2 = Belt_Array.concat(part1, /* array */["more"]);

console.log(part2);

console.log(Belt_Array.slice(items, 1, 3));

console.log(Belt_Array.slice(items, 5, 9));

console.log(Belt_Array.slice(items, -3, 2));

console.log(Belt_Array.slice(items, 3, -2));

var optElement = Belt_Array.get(items, 3);

var badOptElement = Belt_Array.get(items, 10);

var badOptElement2 = items[10];

var element = Belt_Array.getExn(items, 3);

var bracketElement = Caml_array.caml_array_get(items, 3);

console.log(optElement);

console.log(badOptElement);

console.log(badOptElement2);

console.log(element);

exports.items = items;
exports.multiples = multiples;
exports.sqrtPlusOne = sqrtPlusOne;
exports.roots = roots;
exports.more = more;
exports.joined = joined;
exports.part1 = part1;
exports.part2 = part2;
exports.optElement = optElement;
exports.badOptElement = badOptElement;
exports.badOptElement2 = badOptElement2;
exports.element = element;
exports.bracketElement = bracketElement;
/*  Not a pure module */
