// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function distance(p0, p1) {
  return Math.sqrt(Math.pow(p0[0] - p1[0], 2.0) + Math.pow(p0[1] - p1[1], 2.0));
}

var startPoint = /* tuple */[
  3.5,
  4.6
];

var endPoint = /* tuple */[
  0.5,
  9.6
];

var result = distance(startPoint, endPoint);

console.log(result);

function distance2(p0, p1) {
  var x0 = p0[0];
  var y0 = p0[1];
  var x1 = p1[0];
  var y1 = p1[1];
  return Math.sqrt(Math.pow(x0 - x1, 2.0) + Math.pow(y0 - y1, 2.0));
}

exports.distance = distance;
exports.startPoint = startPoint;
exports.endPoint = endPoint;
exports.result = result;
exports.distance2 = distance2;
/* result Not a pure module */
