// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ShirtSize$Collections = require("./ShirtSize.bs.js");

var myShirt = /* XLarge */[1];

var myPrice = ShirtSize$Collections.price(myShirt);

console.log(ShirtSize$Collections.toFixed(myPrice, 2));

exports.myShirt = myShirt;
exports.myPrice = myPrice;
/* myPrice Not a pure module */
