// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function intReducer(accumulator, item) {
  return accumulator + (String(item) + ", ");
}

function stringOfIntList(items) {
  return "[" + (Belt_List.reduce(items, "", intReducer) + "]");
}

var items = /* :: */[
  10,
  /* :: */[
    11,
    /* :: */[
      12,
      /* :: */[
        13,
        /* :: */[
          14,
          /* :: */[
            15,
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

console.log(stringOfIntList(items));

function floatReducer(accumulator, item) {
  return accumulator + (Pervasives.string_of_float(item) + ", ");
}

function stringOfFloatList(items) {
  return "[" + (Belt_List.reduce(items, "", floatReducer) + "]");
}

var floatItems = /* :: */[
  3.6,
  /* :: */[
    7.9,
    /* :: */[
      8.25,
      /* :: */[
        41.0,
        /* [] */0
      ]
    ]
  ]
];

console.log(stringOfFloatList(floatItems));

function stringOfList(items, stringify) {
  var elementReducer = function (accumulator, item) {
    return accumulator + (Curry._1(stringify, item) + ", ");
  };
  return "[" + (Belt_List.reduce(items, "", elementReducer) + "]");
}

console.log(stringOfList(items, (function (prim) {
            return String(prim);
          })));

console.log(stringOfList(floatItems, Pervasives.string_of_float));

exports.intReducer = intReducer;
exports.stringOfIntList = stringOfIntList;
exports.items = items;
exports.floatReducer = floatReducer;
exports.stringOfFloatList = stringOfFloatList;
exports.floatItems = floatItems;
exports.stringOfList = stringOfList;
/*  Not a pure module */
