// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function dewpoint(param) {
  return param[0][0] - (100.0 - param[1][0]) / 5.0;
}

var got = dewpoint(/* tuple */[
      /* Celcius */[12.5],
      /* Percent */[30]
    ]);

console.log(got);

function dewpoint$1(param) {
  return param[0][0] - (100.0 - param[1][0]) / 5.0;
}

var got$1 = dewpoint$1(/* tuple */[
      /* Celcius */[5],
      /* Percent */[49]
    ]);

console.log(got$1);

exports.dewpoint = dewpoint$1;
exports.got = got$1;
/* got Not a pure module */
