// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var items = /* array */[
  10,
  11,
  12,
  13,
  14,
  15,
  16
];

console.log(items);

exports.items = items;
/*  Not a pure module */
