// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ShirtSize$Collections = require("./ShirtSize.bs.js");

var order1 = /* tuple */[
  3,
  /* Medium */1
];

var order2 = /* tuple */[
  5,
  /* XLarge */[3]
];

function toString(param) {
  return String(param[0]) + (" " + ShirtSize$Collections.toString(param[1]));
}

console.log(toString(order1));

console.log(toString(order2));

exports.order1 = order1;
exports.order2 = order2;
exports.toString = toString;
/*  Not a pure module */
