// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function stringOfColorSpec(cspec) {
  if (typeof cspec === "number") {
    if (cspec === 0) {
      return "rgb(255,255,255)";
    } else {
      return "rgb(0,0,0)";
    }
  } else if (cspec.tag) {
    return "rgb(" + (String(cspec[0]) + ("," + (String(cspec[1]) + ("," + (String(cspec[2]) + ")")))));
  } else {
    var bytes = 255 * cspec[0];
    return "rgb(" + (String(bytes) + ("," + (String(bytes) + ("," + (String(bytes) + ")")))));
  }
}

console.log("rgb(255,255,255)");

console.log("rgb(0,0,0)");

console.log(stringOfColorSpec(/* Gray */Block.__(0, [0.5])));

console.log(stringOfColorSpec(/* RGB */Block.__(1, [
            64,
            128,
            192
          ])));

exports.stringOfColorSpec = stringOfColorSpec;
/*  Not a pure module */
