// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function shirtSizeOfString(str) {
  switch (str) {
    case "L" : 
        return /* Large */2;
    case "M" : 
        return /* Medium */1;
    case "S" : 
        return /* Small */0;
    case "XL" : 
        return /* XLarge */[1];
    case "XXL" : 
        return /* XLarge */[2];
    case "XXXL" : 
        return /* XLarge */[3];
    case "XXXXL" : 
        return /* XLarge */[4];
    default:
      return undefined;
  }
}

function price(size) {
  if (size !== undefined) {
    var match = size;
    if (typeof match === "number") {
      switch (match) {
        case 0 : 
            return 11.00;
        case 1 : 
            return 12.50;
        case 2 : 
            return 14.00;
        
      }
    } else {
      return 16.00 + (match[0] - 1 | 0) * 0.50;
    }
  }
  
}

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

function displayPrice(input) {
  var size = shirtSizeOfString(input);
  var amount = price(size);
  var text;
  if (amount !== undefined) {
    var costStr = amount.toFixed(2);
    text = "Your " + (String(input) + (" shirt costs \$" + (String(costStr) + ".")));
  } else {
    text = "Cannot determine price for " + (String(input) + "");
  }
  console.log(text);
  return /* () */0;
}

displayPrice("XXL");

displayPrice("Foo");

exports.shirtSizeOfString = shirtSizeOfString;
exports.price = price;
exports.toFixed = toFixed;
exports.displayPrice = displayPrice;
/*  Not a pure module */
