// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

var bigSize = /* XLarge */[1];

var veryBigSize = /* XLarge */[3];

function price(size) {
  if (typeof size === "number") {
    switch (size) {
      case 0 : 
          return 11.00;
      case 1 : 
          return 12.50;
      case 2 : 
          return 14.00;
      
    }
  } else {
    return 16.00 + (size[0] - 1 | 0) * 0.5;
  }
}

console.log(price(/* Medium */1));

console.log(price(bigSize));

console.log(price(veryBigSize));

function stringOfShirtSize(size) {
  if (typeof size === "number") {
    switch (size) {
      case 0 : 
          return "S";
      case 1 : 
          return "M";
      case 2 : 
          return "L";
      
    }
  } else {
    return $$String.make(size[0], /* "X" */88) + "L";
  }
}

console.log(stringOfShirtSize(veryBigSize));

function shirtSizeOfString(str) {
  switch (str) {
    case "L" : 
        return /* Large */2;
    case "M" : 
        return /* Medium */1;
    case "S" : 
        return /* Small */0;
    case "XL" : 
        return /* XLarge */[1];
    case "XXL" : 
        return /* XLarge */[2];
    case "XXXL" : 
        return /* XLarge */[3];
    case "XXXXL" : 
        return /* XLarge */[4];
    default:
      return /* Medium */1;
  }
}

var mySize = /* Medium */1;

exports.mySize = mySize;
exports.bigSize = bigSize;
exports.veryBigSize = veryBigSize;
exports.price = price;
exports.stringOfShirtSize = stringOfShirtSize;
exports.shirtSizeOfString = shirtSizeOfString;
/*  Not a pure module */
