// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function calcPercent(score, max) {
  return /* Percent */[score[0] / max[0] * 100.0];
}

var match = calcPercent(/* Score */[40], /* Score */[75]);

var result = match[0];

console.log("Good result is " + (String(result) + ""));

var person = /* UserId */[60];

exports.person = person;
exports.calcPercent = calcPercent;
exports.result = result;
/* match Not a pure module */
