// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Dataset = /* module */[];

var Data = /* module */[];

var Legend = /* module */[];

var Tickmark = /* module */[];

var Axis = /* module */[/* Tickmark */Tickmark];

var Scale = /* module */[];

var Option = /* module */[];

var Params = /* module */[];

exports.Dataset = Dataset;
exports.Data = Data;
exports.Legend = Legend;
exports.Axis = Axis;
exports.Scale = Scale;
exports.Option = Option;
exports.Params = Params;
/* No side effect */
