// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Shirt$ReactTemplate = require("./Shirt.bs.js");

var component = ReasonReact.statelessComponent("OrderItem");

function make(order, deleteFunction, editFunction, editing, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("tr", {
                          className: editing ? "editRow" : "normalRow"
                        }, React.createElement("td", undefined, String(order[/* quantity */1])), React.createElement("td", undefined, Shirt$ReactTemplate.Size[/* toString */0](order[/* size */2])), React.createElement("td", undefined, Shirt$ReactTemplate.Sleeve[/* toString */0](order[/* sleeve */3])), React.createElement("td", undefined, Shirt$ReactTemplate.Color[/* toString */0](order[/* color */4])), React.createElement("td", undefined, Shirt$ReactTemplate.Pattern[/* toString */0](order[/* pattern */5])), React.createElement("td", undefined, React.createElement("button", {
                                  onClick: editFunction
                                }, "Edit"), React.createElement("button", {
                                  onClick: deleteFunction
                                }, "Delete")));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var RR = 0;

exports.RR = RR;
exports.component = component;
exports.make = make;
/* component Not a pure module */
