// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

var match = Json.parse("\"two words\"");

var decodedStr = match !== undefined ? Json_decode.string(Caml_option.valFromOption(match)) : "";

console.log(decodedStr);

function floatArrayDecoder(param) {
  return Json_decode.array(Json_decode.$$float, param);
}

var decodedArray = Belt_Option.mapWithDefault(Json.parse("[3.4, 5.6, 7.8]"), /* array */[], floatArrayDecoder);

console.log(decodedArray);

var match$1 = Json.parse("{\"size\": \"XXL\", \"qty\": 10}");

var decodedObj = match$1 !== undefined ? Json_decode.field("qty", Json_decode.$$int, Caml_option.valFromOption(match$1)) : 0;

console.log(decodedObj);

var objStats = "{\"title\": \"color\",\n  \"choices\": [\"White\", \"Blue\", \"Red\", \"Green\", \"Brown\"],\n  \"totals\": [118, 114, 73, 67,28]}\n";

var match$2 = Json.parse(objStats);

var colorStats;

if (match$2 !== undefined) {
  var jsonObj = Caml_option.valFromOption(match$2);
  colorStats = /* record */[
    /* title */Json_decode.field("title", Json_decode.string, jsonObj),
    /* choices */Json_decode.field("choices", (function (param) {
            return Json_decode.array(Json_decode.string, param);
          }), jsonObj),
    /* totals */Json_decode.field("totals", (function (param) {
            return Json_decode.array(Json_decode.$$int, param);
          }), jsonObj)
  ];
} else {
  colorStats = /* record */[
    /* title */"",
    /* choices : array */[],
    /* totals : array */[]
  ];
}

console.log(colorStats);

var sleeveStats_001 = /* choices : array */[
  "short sleeve",
  "long sleeve",
  "extra-long sleeve"
];

var sleeveStats_002 = /* totals : array */[
  129,
  217,
  54
];

var sleeveStats = /* record */[
  /* title */"sleeve",
  sleeveStats_001,
  sleeveStats_002
];

var sleeveJson = Json_encode.object_(/* :: */[
      /* tuple */[
        "title",
        "sleeve"
      ],
      /* :: */[
        /* tuple */[
          "choices",
          sleeveStats_001
        ],
        /* :: */[
          /* tuple */[
            "totals",
            Json_encode.array((function (prim) {
                    return prim;
                  }), sleeveStats_002)
          ],
          /* [] */0
        ]
      ]
    ]);

console.log(Json.stringify(sleeveJson));

var D = 0;

var E = 0;

exports.D = D;
exports.decodedStr = decodedStr;
exports.floatArrayDecoder = floatArrayDecoder;
exports.decodedArray = decodedArray;
exports.decodedObj = decodedObj;
exports.objStats = objStats;
exports.colorStats = colorStats;
exports.sleeveStats = sleeveStats;
exports.E = E;
exports.sleeveJson = sleeveJson;
/* match Not a pure module */
