// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var rightNow = (
 function () {
  var d = new Date();
  return d.toString();
 }()
);

var message = "It is now " + rightNow;

console.log(message);

exports.rightNow = rightNow;
exports.message = message;
/* rightNow Not a pure module */
