// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var metaData = {
  delimiter: ",",
  linebreak: "\n",
  aborted: false,
  fields: /* array */[
    "Quantity",
    "Size",
    "Color"
  ],
  truncated: false
};

console.log(metaData.fields);

console.log(metaData.truncated);

var errExample = {
  type: "Quotes",
  code: "InvalidQuotes",
  message: "Trailing quote on quoted field is malformed",
  row: 1,
  index: 30
};

console.log(errExample.type);

exports.metaData = metaData;
exports.errExample = errExample;
/*  Not a pure module */
