// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function toString(size) {
  if (typeof size === "number") {
    switch (size) {
      case 0 : 
          return "S";
      case 1 : 
          return "M";
      case 2 : 
          return "L";
      
    }
  } else if (size.tag) {
    return $$String.make(size[0], /* "X" */88) + "L";
  } else {
    return $$String.make(size[0], /* "X" */88) + "S";
  }
}

function fromString(str) {
  var s = str.toUpperCase();
  switch (s) {
    case "L" : 
        return /* Large */2;
    case "M" : 
        return /* Medium */1;
    case "S" : 
        return /* Small */0;
    default:
      if ((/^X+S$/).test(s)) {
        return /* XSmall */Block.__(0, [s.length - 1 | 0]);
      } else if ((/^X+L$/).test(s)) {
        return /* XLarge */Block.__(1, [s.length - 1 | 0]);
      } else {
        return undefined;
      }
  }
}

function compareSize(a, b) {
  var exit = 0;
  if (typeof a === "number") {
    exit = 1;
  } else if (a.tag) {
    var s1 = a[0];
    if (typeof b === "number") {
      return 1;
    } else if (b.tag) {
      var s2 = b[0];
      if (s1 === s2) {
        return 0;
      } else {
        var match = s1 < s2;
        if (match) {
          return -1;
        } else {
          return 1;
        }
      }
    } else {
      exit = 1;
    }
  } else {
    var s1$1 = a[0];
    if (typeof b === "number" || b.tag) {
      return -1;
    } else {
      var s2$1 = b[0];
      if (s1$1 === s2$1) {
        return 0;
      } else {
        var match$1 = s1$1 < s2$1;
        if (match$1) {
          return -1;
        } else {
          return 1;
        }
      }
    }
  }
  if (exit === 1) {
    if (typeof b === "number") {
      return Caml_obj.caml_compare(a, b);
    } else if (b.tag) {
      if (typeof a === "number") {
        return -1;
      } else {
        return Caml_obj.caml_compare(a, b);
      }
    } else {
      return 1;
    }
  }
  
}

var Size = /* module */[
  /* toString */toString,
  /* fromString */fromString,
  /* compareSize */compareSize
];

var SizeComparator = Belt_Id.MakeComparable(/* module */[/* cmp */compareSize]);

function toString$1(sleeve) {
  switch (sleeve) {
    case 0 : 
        return "short sleeve";
    case 1 : 
        return "long sleeve";
    case 2 : 
        return "extra-long sleeve";
    
  }
}

function fromString$1(str) {
  var match = str.toLowerCase();
  switch (match) {
    case "long" : 
        return /* Long */1;
    case "short" : 
        return /* Short */0;
    case "xlong" : 
        return /* XLong */2;
    default:
      return undefined;
  }
}

var Sleeve = /* module */[
  /* toString */toString$1,
  /* fromString */fromString$1
];

var cmp = Caml_obj.caml_compare;

var SleeveComparator = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

function toString$2(color) {
  switch (color) {
    case 0 : 
        return "white";
    case 1 : 
        return "blue";
    case 2 : 
        return "red";
    case 3 : 
        return "green";
    case 4 : 
        return "brown";
    
  }
}

function fromString$2(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "blue" : 
        return /* Blue */1;
    case "brown" : 
        return /* Brown */4;
    case "green" : 
        return /* Green */3;
    case "red" : 
        return /* Red */2;
    case "white" : 
        return /* White */0;
    default:
      return undefined;
  }
}

var Color = /* module */[
  /* toString */toString$2,
  /* fromString */fromString$2
];

var cmp$1 = Caml_obj.caml_compare;

var ColorComparator = Belt_Id.MakeComparable(/* module */[/* cmp */cmp$1]);

function toString$3(pattern) {
  switch (pattern) {
    case 0 : 
        return "solid";
    case 1 : 
        return "pinstripe";
    case 2 : 
        return "check";
    
  }
}

function fromString$3(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "check" : 
    case "checked" : 
        return /* Check */2;
    case "pinstripe" : 
        return /* Pinstripe */1;
    case "solid" : 
        return /* Solid */0;
    default:
      return undefined;
  }
}

var Pattern = /* module */[
  /* toString */toString$3,
  /* fromString */fromString$3
];

var cmp$2 = Caml_obj.caml_compare;

var PatternComparator = Belt_Id.MakeComparable(/* module */[/* cmp */cmp$2]);

function toString$4(cuff) {
  switch (cuff) {
    case 0 : 
        return "button";
    case 1 : 
        return "french";
    case 2 : 
        return "none";
    
  }
}

function fromString$4(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "button" : 
        return /* Button */0;
    case "french" : 
        return /* French */1;
    case "" : 
    case "nocuff" : 
    case "none" : 
        return /* NoCuff */2;
    default:
      return undefined;
  }
}

var Cuff = /* module */[
  /* toString */toString$4,
  /* fromString */fromString$4
];

var cmp$3 = Caml_obj.caml_compare;

var CuffComparator = Belt_Id.MakeComparable(/* module */[/* cmp */cmp$3]);

function toString$5(collar) {
  switch (collar) {
    case 0 : 
        return "button";
    case 1 : 
        return "straight";
    case 2 : 
        return "spread";
    
  }
}

function fromString$5(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "button" : 
        return /* Button */0;
    case "spread" : 
        return /* Spread */2;
    case "straight" : 
        return /* Straight */1;
    default:
      return undefined;
  }
}

var Collar = /* module */[
  /* toString */toString$5,
  /* fromString */fromString$5
];

var cmp$4 = Caml_obj.caml_compare;

var CollarComparator = Belt_Id.MakeComparable(/* module */[/* cmp */cmp$4]);

console.log("Sleeve:", /* Long */1);

var otherOrder = /* record */[
  /* quantity */2,
  /* size : Medium */1,
  /* sleeve : Long */1,
  /* color : White */0,
  /* pattern : Solid */0,
  /* cuff : French */1,
  /* collar : Button */0
];

console.log("Cuff:", /* French */1);

var myOrder = /* record */[
  /* quantity */2,
  /* size : Medium */1,
  /* sleeve : Long */1,
  /* color : Blue */1,
  /* pattern : Solid */0,
  /* cuff : Button */0,
  /* collar : Button */0
];

exports.Size = Size;
exports.SizeComparator = SizeComparator;
exports.Sleeve = Sleeve;
exports.SleeveComparator = SleeveComparator;
exports.Color = Color;
exports.ColorComparator = ColorComparator;
exports.Pattern = Pattern;
exports.PatternComparator = PatternComparator;
exports.Cuff = Cuff;
exports.CuffComparator = CuffComparator;
exports.Collar = Collar;
exports.CollarComparator = CollarComparator;
exports.myOrder = myOrder;
exports.otherOrder = otherOrder;
/* SizeComparator Not a pure module */
