// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Notice$ReactTemplate = require("./Notice.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Notice$ReactTemplate.make("Total file size 1280 bytes", "#000", "information", /* array */[])), "info");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Notice$ReactTemplate.make("Variable x is unused", "#FF8C00", "warning", /* array */[])), "warn");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Notice$ReactTemplate.make("Variable y is not defined", "#8B0000", "error", /* array */[])), "err");

/*  Not a pure module */
