// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Animal$ReactTemplate = require("./Animal.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Animal$ReactTemplate.make("bird", "Ella", /* array */[])), "image1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Animal$ReactTemplate.make("cat", "Marco", /* array */[])), "image2");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Animal$ReactTemplate.make("dog", "Lady", /* array */[])), "image3");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Animal$ReactTemplate.make("fish", "Kim", /* array */[])), "image4");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Animal$ReactTemplate.make("foo", "Alex", /* array */[])), "image5");

/*  Not a pure module */
