// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var DefaultParams$Functions = require("./DefaultParams.bs.js");

function usPayment(param) {
  var func = function (param$1, param$2, param$3) {
    return DefaultParams$Functions.payment(param, param$1, param$2, param$3);
  };
  return (function (param) {
      return Curry._2(func, param, 30);
    });
}

function ukPayment(param) {
  var func = function (param$1, param$2, param$3) {
    return DefaultParams$Functions.payment(param, param$1, param$2, param$3);
  };
  return (function (param) {
      return Curry._2(func, param, 25);
    });
}

function dePayment(param) {
  var func = function (param$1, param$2, param$3) {
    return DefaultParams$Functions.payment(param, param$1, param$2, param$3);
  };
  return (function (param) {
      return Curry._2(func, param, 20);
    });
}

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

console.log("Loan of 10000 at 5%");

console.log("US: $", Curry._1(usPayment(10000.0)(5.0), /* () */0).toFixed(2));

console.log("UK: £", Curry._1(ukPayment(10000.0)(5.0), /* () */0).toFixed(2));

console.log("DE: €", Curry._1(dePayment(10000.0)(5.0), /* () */0).toFixed(2));

exports.usPayment = usPayment;
exports.ukPayment = ukPayment;
exports.dePayment = dePayment;
exports.toFixed = toFixed;
/*  Not a pure module */
