// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function avg(a, b) {
  return (a + b) / 2.0;
}

console.log("Average of 3 and 4", (3.0 + 4.0) / 2.0);

console.log("Average of 3?!", (function (param) {
        return avg(3.0, param);
      }));

function call(country, area, number) {
  return country + (" " + (area + (" " + number)));
}

function callGermany(param, param$1) {
  return call("049", param, param$1);
}

function callBerlin(param) {
  return callGermany("030", param);
}

console.log("Call Kim at", "49 030 118 99");

console.log("Call Germany:", callGermany);

console.log("Call Berlin:", callBerlin);

console.log("Call someone in Germany:", callGermany("040", "118 01"));

console.log("Call someone in Berlin:", callBerlin("118 23"));

exports.avg = avg;
exports.call = call;
exports.callGermany = callGermany;
exports.callBerlin = callBerlin;
/*  Not a pure module */
