// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function discount(original, percent) {
  return original * (1 - percent / 100);
}

function halfOff(param) {
  return discount(param, 50);
}

function tenPercentOff(param) {
  return discount(param, 10);
}

function fmt(param) {
  return param.toFixed(2);
}

var result = fmt(100 * (1 - 5 / 100));

console.log("discount of 5% off \$100 is \$" + (String(result) + ""));

var result$1 = fmt(65 * (1 - 50 / 100));

console.log("half off \$65 is \$" + (String(result$1) + ""));

var result$2 = fmt(7.99 * (1 - 10 / 100));

console.log("ten percent off \$7.99 is \$" + (String(result$2) + ""));

exports.discount = discount;
exports.halfOff = halfOff;
exports.tenPercentOff = tenPercentOff;
exports.fmt = fmt;
exports.result = result$2;
/* result Not a pure module */
