// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function avg(a, b) {
  return (a + b) / 2.0;
}

console.log("Amount per month: $", (42.99).toFixed(2));

var amount = 42.99;

exports.avg = avg;
exports.amount = amount;
/*  Not a pure module */
