// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function isPalindrome2(word) {
  var s = word;
  var _start = 0;
  var _finish = word.length - 1 | 0;
  while(true) {
    var finish = _finish;
    var start = _start;
    if ((finish - start | 0) <= 1) {
      return true;
    } else if (s[start] === s[finish]) {
      _finish = finish - 1 | 0;
      _start = start + 1 | 0;
      continue ;
    } else {
      return false;
    }
  };
}

console.log(isPalindrome2("civic"));

console.log(isPalindrome2("deed"));

console.log(isPalindrome2("runner"));

console.log(isPalindrome2("fnord"));

function repeat(s, n) {
  var _accumulator = "";
  var _counter = n;
  while(true) {
    var counter = _counter;
    var accumulator = _accumulator;
    if (counter !== 0) {
      _counter = counter - 1 | 0;
      _accumulator = accumulator + s;
      continue ;
    } else {
      return accumulator;
    }
  };
}

var testString = repeat("a", 50000);

function repeatTest(_n, _accumulatedTime) {
  while(true) {
    var accumulatedTime = _accumulatedTime;
    var n = _n;
    if (n !== 0) {
      var startTime = Date.now();
      isPalindrome2(testString);
      var endTime = Date.now();
      _accumulatedTime = accumulatedTime + (endTime - startTime);
      _n = n - 1 | 0;
      continue ;
    } else {
      return accumulatedTime;
    }
  };
}

var totalTime = repeatTest(1000, 0.0);

console.log("My version of isPalindrome2 (string from parameter): Average time in msec:", totalTime / 1000.0);

exports.isPalindrome2 = isPalindrome2;
exports.repeat = repeat;
exports.testString = testString;
exports.repeatTest = repeatTest;
exports.totalTime = totalTime;
/*  Not a pure module */
