// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Author = /* module */[];

var Book = /* module */[/* Author */Author];

console.log(/* lastName */"Stephenson");

var b = /* record */[
  /* title */"Anathem",
  /* author : record */[
    /* firstName */"Neal",
    /* lastName */"Stephenson"
  ],
  /* isbn13 */"978-0-06-147409-5"
];

exports.Book = Book;
exports.b = b;
/*  Not a pure module */
