// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var $$String = require("bs-platform/lib/js/string.js");

function toString(size) {
  if (typeof size === "number") {
    switch (size) {
      case 0 : 
          return "S";
      case 1 : 
          return "M";
      case 2 : 
          return "L";
      
    }
  } else if (size.tag) {
    return $$String.make(size[0], /* "X" */88) + "L";
  } else {
    return $$String.make(size[0], /* "X" */88) + "S";
  }
}

function fromString(str) {
  var s = str.toUpperCase();
  switch (s) {
    case "L" : 
        return /* Large */2;
    case "M" : 
        return /* Medium */1;
    case "S" : 
        return /* Small */0;
    default:
      if ((/^X+S$/).test(s)) {
        return /* XSmall */Block.__(0, [s.length - 1 | 0]);
      } else if ((/^X+L$/).test(s)) {
        return /* XLarge */Block.__(1, [s.length - 1 | 0]);
      } else {
        return undefined;
      }
  }
}

var Size = /* module */[
  /* toString */toString,
  /* fromString */fromString
];

function toString$1(sleeve) {
  switch (sleeve) {
    case 0 : 
        return "short sleeve";
    case 1 : 
        return "long sleeve";
    case 2 : 
        return "extra-long sleeve";
    
  }
}

function fromString$1(str) {
  var match = str.toLowerCase();
  switch (match) {
    case "long" : 
        return /* Long */1;
    case "short" : 
        return /* Short */0;
    case "xlong" : 
        return /* XLong */2;
    default:
      return undefined;
  }
}

var Sleeve = /* module */[
  /* toString */toString$1,
  /* fromString */fromString$1
];

function toString$2(color) {
  switch (color) {
    case 0 : 
        return "white";
    case 1 : 
        return "blue";
    case 2 : 
        return "red";
    case 3 : 
        return "green";
    case 4 : 
        return "brown";
    
  }
}

function fromString$2(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "blue" : 
        return /* Blue */1;
    case "brown" : 
        return /* Brown */4;
    case "green" : 
        return /* Green */3;
    case "red" : 
        return /* Red */2;
    case "white" : 
        return /* White */0;
    default:
      return undefined;
  }
}

var Color = /* module */[
  /* toString */toString$2,
  /* fromString */fromString$2
];

function toString$3(pattern) {
  switch (pattern) {
    case 0 : 
        return "solid";
    case 1 : 
        return "pinstripe";
    case 2 : 
        return "check";
    
  }
}

function fromString$3(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "check" : 
    case "checked" : 
        return /* Check */2;
    case "pinstripe" : 
        return /* Pinstripe */1;
    case "solid" : 
        return /* Solid */0;
    default:
      return undefined;
  }
}

var Pattern = /* module */[
  /* toString */toString$3,
  /* fromString */fromString$3
];

function toString$4(cuff) {
  switch (cuff) {
    case 0 : 
        return "button";
    case 1 : 
        return "french";
    case 2 : 
        return "none";
    
  }
}

function fromString$4(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "button" : 
        return /* Button */0;
    case "french" : 
        return /* French */1;
    case "" : 
    case "nocuff" : 
    case "none" : 
        return /* NoCuff */2;
    default:
      return undefined;
  }
}

var Cuff = /* module */[
  /* toString */toString$4,
  /* fromString */fromString$4
];

function toString$5(collar) {
  switch (collar) {
    case 0 : 
        return "button";
    case 1 : 
        return "straight";
    case 2 : 
        return "spread";
    
  }
}

function fromString$5(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "button" : 
        return /* Button */0;
    case "spread" : 
        return /* Spread */2;
    case "straight" : 
        return /* Straight */1;
    default:
      return undefined;
  }
}

var Collar = /* module */[
  /* toString */toString$5,
  /* fromString */fromString$5
];

console.log("Sleeve:", /* Long */1);

var otherOrder = /* record */[
  /* quantity */2,
  /* size : Medium */1,
  /* sleeve : Long */1,
  /* color : White */0,
  /* pattern : Solid */0,
  /* cuff : French */1,
  /* collar : Button */0
];

console.log("Cuff:", /* French */1);

var myOrder = /* record */[
  /* quantity */2,
  /* size : Medium */1,
  /* sleeve : Long */1,
  /* color : Blue */1,
  /* pattern : Solid */0,
  /* cuff : Button */0,
  /* collar : Button */0
];

exports.Size = Size;
exports.Sleeve = Sleeve;
exports.Color = Color;
exports.Pattern = Pattern;
exports.Cuff = Cuff;
exports.Collar = Collar;
exports.myOrder = myOrder;
exports.otherOrder = otherOrder;
/*  Not a pure module */
