// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function happyBirthday(someone) {
  someone[/* age */1] = someone[/* age */1] + 1 | 0;
  return /* () */0;
}

var friend = /* record */[
  /* name */"Juanita Fulano",
  /* age */34
];

happyBirthday(friend);

console.log(friend[/* age */1]);

exports.happyBirthday = happyBirthday;
exports.friend = friend;
/*  Not a pure module */
