// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

console.log("Size:", /* XLarge */Block.__(1, [1]));

var otherOrder_001 = /* size : XLarge */Block.__(1, [1]);

var otherOrder = /* record */[
  /* quantity */1,
  otherOrder_001,
  /* sleeve : Long */1,
  /* color : White */0,
  /* pattern : Solid */0,
  /* cuff : French */1,
  /* collar : Button */0
];

console.log("Cuff:", /* French */1);

var myOrder = /* record */[
  /* quantity */1,
  /* size : XLarge */Block.__(1, [1]),
  /* sleeve : Long */1,
  /* color : Blue */1,
  /* pattern : Solid */0,
  /* cuff : Button */0,
  /* collar : Button */0
];

exports.myOrder = myOrder;
exports.otherOrder = otherOrder;
/*  Not a pure module */
