// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.js");
var Process = require("process");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Stats$InteropServer = require("./Stats.bs.js");

function onListen(e) {
  var exit = 0;
  var val;
  try {
    val = e;
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    console.log("Listening at http://127.0.0.1:3000");
    return /* () */0;
  }
  
}

var app = Express.express(/* () */0);

var server = Express.App[/* listen */21](app, 3000, onListen, /* () */0);

Express.App[/* get */4](app, "/", Express.Middleware[/* from */5]((function (param, param$1) {
            var partial_arg = {
              root: "./dist"
            };
            var partial_arg$1 = Express.Response[/* sendFile */1];
            return (function (param) {
                return partial_arg$1("index.html", partial_arg, param);
              });
          })));

Express.App[/* get */4](app, "/json", Express.Middleware[/* from */5]((function (param, req) {
            var __x = Json_decode.string(Express.Request[/* query */19](req)["choice"]);
            var partial_arg = Stats$InteropServer.processFile("orders.csv", __x);
            var partial_arg$1 = Express.Response[/* sendJson */3];
            return (function (param) {
                return partial_arg$1(partial_arg, param);
              });
          })));

Express.App[/* get */4](app, "/:filename", Express.Middleware[/* from */5]((function (param, req) {
            var partial_arg = {
              root: "./dist"
            };
            var partial_arg$1 = Json_decode.string(Express.Request[/* params */0](req)["filename"]);
            var partial_arg$2 = Express.Response[/* sendFile */1];
            return (function (param) {
                return partial_arg$2(partial_arg$1, partial_arg, param);
              });
          })));

exports.onListen = onListen;
exports.app = app;
exports.server = server;
/* app Not a pure module */
