// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Map = require("bs-platform/lib/js/belt_Map.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Papaparse = require("papaparse");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Shirt$InteropServer = require("./Shirt.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var $$Error = /* module */[];

var Meta = /* module */[];

var Results = /* module */[];

function optFloat(str) {
  var exit = 0;
  var fNum;
  try {
    fNum = Caml_format.caml_float_of_string(str);
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Caml_builtin_exceptions.failure) {
      if (exn[1] === "float_of_string") {
        return undefined;
      } else {
        throw exn;
      }
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    return fNum;
  }
  
}

function optInt(str) {
  var exit = 0;
  var anInt;
  try {
    anInt = Caml_format.caml_int_of_string(str);
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Caml_builtin_exceptions.failure) {
      if (exn[1] === "int_of_string") {
        return undefined;
      } else {
        throw exn;
      }
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    return anInt;
  }
  
}

function map2(optX, optY, f) {
  if (optX !== undefined && optY !== undefined) {
    return Caml_option.some(Curry._2(f, Caml_option.valFromOption(optX), Caml_option.valFromOption(optY)));
  }
  
}

function lineReducer(acc, items) {
  if (items.length !== 7) {
    return acc;
  } else {
    var orderRecord = map2(map2(map2(map2(map2(map2(map2(/* record */[
                                  /* quantity */0,
                                  /* size : Small */0,
                                  /* sleeve : Short */0,
                                  /* color : White */0,
                                  /* pattern : Solid */0,
                                  /* cuff : Button */0,
                                  /* collar : Straight */1
                                ], optInt(Caml_array.caml_array_get(items, 0)), (function (result, n) {
                                    return /* record */[
                                            /* quantity */n,
                                            /* size */result[/* size */1],
                                            /* sleeve */result[/* sleeve */2],
                                            /* color */result[/* color */3],
                                            /* pattern */result[/* pattern */4],
                                            /* cuff */result[/* cuff */5],
                                            /* collar */result[/* collar */6]
                                          ];
                                  })), Shirt$InteropServer.Size[/* fromString */1](Caml_array.caml_array_get(items, 1)), (function (result, sz) {
                                return /* record */[
                                        /* quantity */result[/* quantity */0],
                                        /* size */sz,
                                        /* sleeve */result[/* sleeve */2],
                                        /* color */result[/* color */3],
                                        /* pattern */result[/* pattern */4],
                                        /* cuff */result[/* cuff */5],
                                        /* collar */result[/* collar */6]
                                      ];
                              })), Shirt$InteropServer.Color[/* fromString */1](Caml_array.caml_array_get(items, 2)), (function (result, c) {
                            return /* record */[
                                    /* quantity */result[/* quantity */0],
                                    /* size */result[/* size */1],
                                    /* sleeve */result[/* sleeve */2],
                                    /* color */c,
                                    /* pattern */result[/* pattern */4],
                                    /* cuff */result[/* cuff */5],
                                    /* collar */result[/* collar */6]
                                  ];
                          })), Shirt$InteropServer.Pattern[/* fromString */1](Caml_array.caml_array_get(items, 3)), (function (result, pat) {
                        return /* record */[
                                /* quantity */result[/* quantity */0],
                                /* size */result[/* size */1],
                                /* sleeve */result[/* sleeve */2],
                                /* color */result[/* color */3],
                                /* pattern */pat,
                                /* cuff */result[/* cuff */5],
                                /* collar */result[/* collar */6]
                              ];
                      })), Shirt$InteropServer.Collar[/* fromString */1](Caml_array.caml_array_get(items, 4)), (function (result, coll) {
                    return /* record */[
                            /* quantity */result[/* quantity */0],
                            /* size */result[/* size */1],
                            /* sleeve */result[/* sleeve */2],
                            /* color */result[/* color */3],
                            /* pattern */result[/* pattern */4],
                            /* cuff */result[/* cuff */5],
                            /* collar */coll
                          ];
                  })), Shirt$InteropServer.Sleeve[/* fromString */1](Caml_array.caml_array_get(items, 5)), (function (result, sleeve) {
                return /* record */[
                        /* quantity */result[/* quantity */0],
                        /* size */result[/* size */1],
                        /* sleeve */sleeve,
                        /* color */result[/* color */3],
                        /* pattern */result[/* pattern */4],
                        /* cuff */result[/* cuff */5],
                        /* collar */result[/* collar */6]
                      ];
              })), Shirt$InteropServer.Cuff[/* fromString */1](Caml_array.caml_array_get(items, 6)), (function (result, cuff) {
            return /* record */[
                    /* quantity */result[/* quantity */0],
                    /* size */result[/* size */1],
                    /* sleeve */result[/* sleeve */2],
                    /* color */result[/* color */3],
                    /* pattern */result[/* pattern */4],
                    /* cuff */cuff,
                    /* collar */result[/* collar */6]
                  ];
          }));
    if (orderRecord !== undefined) {
      return /* :: */[
              orderRecord,
              acc
            ];
    } else {
      return acc;
    }
  }
}

function makeObject(title, distribution, toString) {
  var pairs = Belt_Map.reduce(distribution, /* array */[], (function (acc, key, value) {
          return Belt_Array.concat(acc, /* array */[/* tuple */[
                        Curry._1(toString, key),
                        value
                      ]]);
        }));
  var match = Belt_Array.unzip(pairs);
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "title",
                title
              ],
              /* :: */[
                /* tuple */[
                  "choices",
                  match[0]
                ],
                /* :: */[
                  /* tuple */[
                    "totals",
                    Json_encode.array((function (prim) {
                            return prim;
                          }), match[1])
                  ],
                  /* [] */0
                ]
              ]
            ]);
}

function statisticsToJson(orders, column) {
  var makeDistro = function (comparator, getter) {
    return Belt_List.reduce(orders, Belt_Map.make(comparator), (function (acc, item) {
                  var n = Belt_Map.getWithDefault(acc, Curry._1(getter, item), 0);
                  return Belt_Map.set(acc, Curry._1(getter, item), n + item[/* quantity */0] | 0);
                }));
  };
  switch (column) {
    case "collar" : 
        return makeObject("Collar", makeDistro(Shirt$InteropServer.CollarComparator, (function (anOrder) {
                          return anOrder[/* collar */6];
                        })), Shirt$InteropServer.Collar[/* toString */0]);
    case "color" : 
        return makeObject("Color", makeDistro(Shirt$InteropServer.ColorComparator, (function (anOrder) {
                          return anOrder[/* color */3];
                        })), Shirt$InteropServer.Color[/* toString */0]);
    case "cuff" : 
        return makeObject("Cuff", makeDistro(Shirt$InteropServer.CuffComparator, (function (anOrder) {
                          return anOrder[/* cuff */5];
                        })), Shirt$InteropServer.Cuff[/* toString */0]);
    case "pattern" : 
        return makeObject("Pattern", makeDistro(Shirt$InteropServer.PatternComparator, (function (anOrder) {
                          return anOrder[/* pattern */4];
                        })), Shirt$InteropServer.Pattern[/* toString */0]);
    case "size" : 
        return makeObject("Size", makeDistro(Shirt$InteropServer.SizeComparator, (function (anOrder) {
                          return anOrder[/* size */1];
                        })), Shirt$InteropServer.Size[/* toString */0]);
    case "sleeve" : 
        return makeObject("Sleeve", makeDistro(Shirt$InteropServer.SleeveComparator, (function (anOrder) {
                          return anOrder[/* sleeve */2];
                        })), Shirt$InteropServer.Sleeve[/* toString */0]);
    default:
      return Json_encode.object_(/* :: */[
                  /* tuple */[
                    "title",
                    "Error"
                  ],
                  /* :: */[
                    /* tuple */[
                      "choices",
                      /* array */[]
                    ],
                    /* :: */[
                      /* tuple */[
                        "totals",
                        Json_encode.array((function (prim) {
                                return prim;
                              }), /* array */[])
                      ],
                      /* [] */0
                    ]
                  ]
                ]);
  }
}

function processFile(inFileName, column) {
  var fileContents = Fs.readFileSync(inFileName, "utf8");
  var parseData = Papaparse.parse(fileContents).data;
  var lines = Belt_Array.slice(parseData, 1, parseData.length - 1 | 0);
  var orders = Belt_Array.reduce(lines, /* [] */0, lineReducer);
  return statisticsToJson(orders, column);
}

var E = 0;

exports.E = E;
exports.$$Error = $$Error;
exports.Meta = Meta;
exports.Results = Results;
exports.optFloat = optFloat;
exports.optInt = optInt;
exports.map2 = map2;
exports.lineReducer = lineReducer;
exports.makeObject = makeObject;
exports.statisticsToJson = statisticsToJson;
exports.processFile = processFile;
/* fs Not a pure module */
