// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var OrderForm$ReactTemplate = require("./OrderForm.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, OrderForm$ReactTemplate.make(/* array */[])), "orderForm");

/*  Not a pure module */
