// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var DiscountPrice$FirstProject = require("./DiscountPrice.bs.js");

var total = DiscountPrice$FirstProject.qty * DiscountPrice$FirstProject.price;

var afterDiscount = total * (1.0 - DiscountPrice$FirstProject.discount);

console.log("Price before discount: $" + (Pervasives.string_of_float(total) + "."));

console.log("Price after discount: $" + (Pervasives.string_of_float(afterDiscount) + "."));

exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
