// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var BadUnicode$FirstProject = require("./BadUnicode.bs.js");

console.log("Prix avant réduction: " + (String(BadUnicode$FirstProject.total) + " €"));

console.log("Prix après réduction: " + (String(BadUnicode$FirstProject.afterDiscount) + " €"));

/*  Not a pure module */
