// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var poem = "The boy stood on the burning deck,\nWhence all but he had fled;\nThe flames that lit the battle\'s wreck...";

console.log(poem);

exports.poem = poem;
/*  Not a pure module */
