// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var discount = 0.05;

var total = 7 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("Prix avant réduction: " + (Pervasives.string_of_float(total) + " €"));

console.log("Prix après réduction: " + (Pervasives.string_of_float(afterDiscount) + " €"));

var qty = 7;

var price = 14.50;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
